print('Hello, World')
print("It's been a long long time")
print('Since Ive memorized your face')
print("It's been four hours now")
print("Since I've wandered through your place")
print("And when I sleep on your couch")
print("I feel very safe")
print("And when you bring the blankets")
print("I cover up my face")
print("I do, love you")